### ISSUE TITLE
feature: control of the timeout

### ISSUE THREAD

**Issue by lacostej** [simonhaenisch/md-to-pdf#101]
**Problem:**

Some of our documents take time to be generated and exceed the default pupeteer 30s timeout.

```
  ✖ generating PDF from doc.md
    → Navigation timeout of 30000 ms exceeded
ListrError: Something went wrong
    at /usr/local/lib/node_modules/md-to-pdf/node_modules/listr/index.js:102:18
    at async main (/usr/local/lib/node_modules/md-to-pdf/dist/cli.js:118:5) {
  errors: [
    TimeoutError: Navigation timeout of 30000 ms exceeded
        at /usr/local/lib/node_modules/md-to-pdf/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106:111
        at async DOMWorld.setContent (/usr/local/lib/node_modules/md-to-pdf/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:146:23)
        at async Page.setContent (/usr/local/lib/node_modules/md-to-pdf/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1097:9)
        at async Object.generateOutput (/usr/local/lib/node_modules/md-to-pdf/dist/lib/generate-output.js:14:5)
        at async Object.convertMdToPdf (/usr/local/lib/node_modules/md-to-pdf/dist/lib/md-to-pdf.js:61:20)
  ],
  context: [Object: null prototype] {}
}
```

**Solution:**

Either
* call [here](https://github.com/simonhaenisch/md-to-pdf/blob/master/src/lib/generate-output.ts#L32
) the `setContent` method passing the puppetteer [options](https://github.com/puppeteer/puppeteer/blob/main/src/common/Page.ts#L1694) .
* call some of the set timeouts options
https://github.com/puppeteer/puppeteer/blob/main/src/common/Page.ts#L917-L943

???

**Comment by simonhaenisch** [comment]
Thanks for the report. I'm wondering whether the best option would be to expose the whole `page` reference, so that you can define a callback via js config, e. g.

```js
module.exports = {
  afterPageInit: (page) => page.setDefaultNavigationTimeout(60000)
}
```

But maybe it's also good to provide a global `--puppeteer-timeout` config option that applies the `timeout` option for all puppeteer related calls.
