### ISSUE TITLE
Error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by Yb-Z** [simonhaenisch/md-to-pdf#109]
I encounter this problem when using md2pdf on macOS. Could anyone help me to solve it? Thank you very much!!!

md-to-pdf version: 5.0.1

```
Error output:

 Error: Failed to launch the browser process!
    dlopen /usr/local/lib/node_modules/md-to-pdf/node_modules/puppeteer/.local-chromium/mac-938248/chrome-mac/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/98.0.4753.0/Chromium Framework: dlopen(/usr/local/lib/node_modules/md-to-pdf/node_modules/puppeteer/.local-chromium/mac-938248/chrome-mac/Chromium.app/Contents/MacOS/../Frameworks/Chromium Framework.framework/Versions/98.0.4753.0/Chromium Framework, 261): Symbol not found: __ZN20wireless_diagnostics6google8protobuf2io16CodedInputStream24default_recursion_limit_E
      Referenced from: /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib
      Expected in: /usr/local/mysql/lib//libprotobuf-lite.dylib


    TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

        at onClose (/usr/local/lib/node_modules/md-to-pdf/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:229:20)
        at ChildProcess.<anonymous> (/usr/local/lib/node_modules/md-to-pdf/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:220:79)
        at ChildProcess.emit (node:events:406:35)
        at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12),
```

**Comment by simonhaenisch** [comment]
Please check https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md.
