### ISSUE TITLE
throw new errors.AssertionError

### ISSUE THREAD

**Issue by ymushet** [simonhaenisch/md-to-pdf#5]
Hi guys, Im getting this error when trying to convert my .md to .pdf with md-to-pdf README.md command. How can I fix this 

> assert.js:42
   throw new errors.AssertionError({

>AssertionError [ERR_ASSERTION]: html-pdf: Failed to load PhantomJS module. You have to set the path to the PhantomJS binary using 'options.phantomPath'
    at new PDF (/Users/ymushet/md-to-pdf/node_modules/html-pdf/lib/pdf.js:38:3)
    at Object.createPdf [as create] (/Users/ymushet/md-to-pdf/node_modules/html-pdf/lib/index.js:10:14)
    at Object.<anonymous> (/Users/ymushet/md-to-pdf/index.js:80:10)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)

**Comment by simonhaenisch** [comment]
Hi,

I haven't had that yet, however I found this related issue: https://github.com/marcbachmann/node-html-pdf/issues/212

Can you try either `npm rebuild phantomjs-prebuilt` or `npm install phantomjs-prebuilt@2.1.3`, plesae?
